// <auto-generated />
namespace ZenithDataLib.Migrations.ZenithData
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NextWeek : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NextWeek));
        
        string IMigrationMetadata.Id
        {
            get { return "201610201942367_NextWeek"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
